"""add encrypted pdn fields and kyc consents

Revision ID: f2ae4905c200
Revises: 537f2396e29a
Create Date: 2026-04-19 03:06:12.439057
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f2ae4905c200'
down_revision: str | Sequence[str] | None = '537f2396e29a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_submissions', sa.Column('consents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('kyc_submissions', sa.Column('resubmit_requested_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('kyc_submissions', sa.Column('previous_submission_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'kyc_submissions', 'kyc_submissions', ['previous_submission_id'], ['id'])
    op.add_column('users', sa.Column('passport_issued_by', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('passport_issue_date', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('registration_address', sa.String(length=512), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'passport_series',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'passport_number',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'passport_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('users', 'passport_series',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'registration_address')
    op.drop_column('users', 'passport_issue_date')
    op.drop_column('users', 'passport_issued_by')
    op.drop_constraint(None, 'kyc_submissions', type_='foreignkey')
    op.drop_column('kyc_submissions', 'previous_submission_id')
    op.drop_column('kyc_submissions', 'resubmit_requested_files')
    op.drop_column('kyc_submissions', 'consents')
    # ### end Alembic commands ###
